import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebar from the docs directory structure.
 * Page ordering is controlled by sidebar_position frontmatter
 * and _category_.json position fields.
 */
const sidebars: SidebarsConfig = {
  getStartedSidebar: [{type: 'autogenerated', dirName: 'get-started'}],
  manualSidebar: [{type: 'autogenerated', dirName: 'manual'}],
};

export default sidebars;
