import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebar from the docs directory structure.
 * Page ordering is controlled by sidebar_position frontmatter
 * and _category_.json position fields.
 */
const sidebars: SidebarsConfig = {
  getStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
